autohome:
  url: https://autohomehost
  home: autohome home GUID
  api_key: autohome API key

zones:
  - id: autohome zone GUID
    name: zone name
    devices:
      - name: thermometer
        type: temperature
        direction: input
        data:
          unit: celsius
          interface: ds18x20
          address: 28-02199245d188
          calibrate: 1.5
          threshold: 0.2
      - name: heater
        type: on-off
        direction: output
        data:
          interface: gpio
          address: 17
          changes:
            - device: thermometer
              direction: increase
          
          

